# Generated by Django 3.2.3 on 2021-07-05 18:22

import Users.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('media', models.FileField(blank=True, default='topics/default.jpg', max_length=256, upload_to=Users.models.upload_to_Topic)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('postedAt', models.DateTimeField(default=datetime.datetime(2021, 7, 5, 23, 52, 19, 225345))),
                ('content', models.TextField(default='')),
                ('upvotes', models.IntegerField(default=0)),
                ('media', models.FileField(blank=True, default='threads/default.jpg', max_length=256, upload_to=Users.models.upload_to_Thread)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likesGiven', models.PositiveIntegerField(default=0)),
                ('organisation', models.TextField(default='')),
                ('photo', models.FileField(blank=True, default='profile/default.jpg', max_length=256, upload_to=Users.models.upload_to_Profile)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('threadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.thread')),
            ],
        ),
    ]
