# Generated by Django 3.2.3 on 2021-05-21 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.AddField(
            model_name='profile',
            name='likesGiven',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 23, 57, 18, 381431)),
        ),
        migrations.AddField(
            model_name='thread',
            name='topicID',
            field=models.ManyToManyField(default=1, to='Users.Topic'),
        ),
    ]
