# Generated by Django 3.2.3 on 2021-07-05 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_alter_thread_postedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 18, 34, 401138)),
        ),
    ]
