# Generated by Django 3.2.3 on 2021-05-21 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_thread_postedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 23, 59, 46, 307538)),
        ),
    ]
