# Generated by Django 3.2.3 on 2021-06-01 19:05

import Users.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_thread_postedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='media',
            field=models.FileField(blank=True, default='threads/default.jpg', max_length=256, upload_to=Users.models.upload_to_Thread),
        ),
        migrations.AddField(
            model_name='topic',
            name='media',
            field=models.FileField(blank=True, default='topics/default.jpg', max_length=256, upload_to=Users.models.upload_to_Topic),
        ),
        migrations.AlterField(
            model_name='thread',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 0, 35, 51, 166410)),
        ),
    ]
