# Generated by Django 3.2.3 on 2021-06-28 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210602_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 1, 44, 59, 673728)),
        ),
        migrations.RemoveField(
            model_name='thread',
            name='topicID',
        ),
        migrations.AddField(
            model_name='thread',
            name='topicID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.topic'),
            preserve_default=False,
        ),
    ]
